### ISSUE TITLE
Nautilus 43 support

### ISSUE THREAD

**Issue by yochananmarqos** [rabbitvcs/rabbitvcs#359]
There are many changes with nautilus-python 4.0 and current Nautilus extensions will not work. See the [4.0.alpha](https://gitlab.gnome.org/GNOME/nautilus-python/-/tags/4.0.alpha) release notes for details about adopting the changes. GNOME 43 will be released in few weeks.

EDIT: See https://gnome.pages.gitlab.gnome.org/nautilus-python/nautilus-python-migrating-to-4.html

**Comment by Forage** [comment]
Debian went ahead and disabled building the extension all together because of it: https://tracker.debian.org/media/packages/r/rabbitvcs/changelog-0.18-4

**Comment by CloCkWeRX** [comment]
Patches welcome for this.

**Comment by philippun1** [comment]
If I update the MenuProvider API, and update depdency from Gtk3.0 to Gtk4.0, the following error happens:
`Traceback (most recent call last):
  File "/home/phil/.local/share/nautilus-python/extensions/rabber.py", line 38, in <module>
    import rabbitvcs.ui.property_page
  File "/home/phil/.local/lib/python3.10/site-packages/rabbitvcs/ui/property_page.py", line 8, in <module>
    import rabbitvcs.ui.widget
  File "/home/phil/.local/lib/python3.10/site-packages/rabbitvcs/ui/widget.py", line 1048, in <module>
    class Clickable(object):
  File "/home/phil/.local/lib/python3.10/site-packages/rabbitvcs/ui/widget.py", line 1059, in Clickable
    _2BUTTON_PRESS = Gdk.EventType._2BUTTON_PRESS
AttributeError: type object 'EventType' has no attribute '_2BUTTON_PRESS'. Did you mean: 'BUTTON_PRESS'?`
Since widget.py is included basically everywhere else, the UI has to be converted to Gtk4 before the nautilus extension could work again with Nautilus 43?

**Comment by philippun1** [comment]
Ok, migrating to gtk4 will be a lot of work... I made a workaround, which works again with Nautilus 43 (icons not working yet): #361 
@CloCkWeRX would this be a viable solution? I had to duplicate some of the sources.

**Comment by yochananmarqos** [comment]
@philippun1 I just tried your #360 PR applied on top of the latest commit a9b4922. The menus and icons work in Nautilus 43.0. However, the Settings won't open:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/rabbitvcs/ui/settings.py", line 420, in <module>
    window = Settings(options.base_dir)
  File "/usr/lib/python3.10/site-packages/rabbitvcs/ui/settings.py", line 82, in __init__
    self.get_widget("enable_attributes").set_active(
AttributeError: 'Settings' object has no attribute 'get_widget'
```

It also does not work with Nemo 5.4.3. Probably because it does not use Gtk4 yet.

```
Traceback (most recent call last):
  File "/usr/share/nemo-python/extensions/RabbitVCS.py", line 91, in <module>
    from rabbitvcs.util.contextmenu import MenuBuilder, MainContextMenu, SEPARATOR, ContextMenuConditions
  File "/usr/lib/python3.10/site-packages/rabbitvcs/util/contextmenu.py", line 33, in <module>
    from .contextmenuitems import *
  File "/usr/lib/python3.10/site-packages/rabbitvcs/util/contextmenuitems.py", line 29, in <module>
    gi.require_version("Gtk", "4.0")
  File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 117, in require_version
    raise ValueError('Namespace %s is already loaded with version %s' %
ValueError: Namespace Gtk is already loaded with version 3.0
```

**Comment by philippun1** [comment]
@yochananmarqos #361 is a quick hack workaround to get it working again with Nautilus 43, which basically duplicates some code to get the Nautilus plugin work with Gtk4 and all the dialogs to work with Gtk3.
#360 is a work in progress of a complete migration to Gtk4, which is not functional right now.

So if you want a somehow working state, you have to use #361. I am currently using this branch and it works so far. But I only tested it with Nautilus 43 on Ubuntu 22.10.

**Comment by yochananmarqos** [comment]
@philippun1 Thanks, forgot to try #361. It's working well so far.

**Comment by sta2m** [comment]
Hi,

Updating my debian distro today and lost RabbitVCS in Nautilus 43. I see #361 but doesn't work here. 
Any help ? 

Thanks ;)

**Comment by sta2m** [comment]
Ok, it's working. Need to do a 

```sudo cp -R /usr/lib/python3/dist-packages/rabbitvcs/ /usr/local/lib/python3.10/dist-packages```

**Comment by yochananmarqos** [comment]
@sta2m That should not be necessary. System packages should never be in `/usr/local/`.

**Comment by sta2m** [comment]
IThx for reply.

I don't know why, but this is the only way I found to got RabbitVCS Ok.
